### ISSUE TITLE
Can't edit scrollback in neovim

### ISSUE THREAD

**Issue by TheButlah** [zellij-org/zellij#2302]
**Basic information**

```
❯ zellij --version
zellij 0.35.2
❯ stty size
48 105
❯ uname -av
Darwin ryan-macbook.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64
```

List of programs you interact with as, `PROGRAM --version`: output cropped meaningful, for example:
```
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info

❯ starship --version
starship 1.13.1
branch:
commit_hash:
build_time:2023-03-10 23:42:58 -05:00
build_env:rustc 1.68.0 (2c8cc3432 2023-03-06),stable-aarch64-apple-darwin
```
<img width="247" alt="Screenshot 2023-03-17 at 7 47 42 PM" src="https://user-images.githubusercontent.com/6969415/226070637-cdc98260-bca3-42f5-8b47-c980307bab6c.png">

Neovim config is the default one (i.e. no config).

**Further information**
The scrollback gets edited correctly when recording with asciinema and *then* opening zellij, but if I instead open zellij without asciinema recording, the scrollback edit just goes to an empty file:

<img width="1721" alt="Screenshot 2023-03-17 at 7 59 16 PM" src="https://user-images.githubusercontent.com/6969415/226071410-ab2993cf-d947-47fd-852a-e0dab0cd2e02.png">

**Comment by imsnif** [comment]
How did you set up neovim as your scrollback editor? could you paste the configuration here? Be it through `$SHELL` or through `scrollback_editor`?

**Comment by TheButlah** [comment]
> How did you set up neovim as your scrollback editor? could you paste the configuration here? Be it through `$SHELL` or through `scrollback_editor`?

```
❯ cat ~/.zshenv
. "$HOME/.cargo/env"
export EDITOR="$(which nvim)"
```

**Comment by TheButlah** [comment]
Is there any further information I can provide? 
I tried the same thing with Ctrl-x Ctrl-e in bash/zsh, and that works properly.

**Comment by imsnif** [comment]
On the flipside, this works perfectly for me and lots of other users - so I can point the finger the other way :)

I'd try to make the problem smaller to find out what the issue is. eg. make the path absolute rather than using a shell invocation with `which`. I believe you as the user are the best positioned person to get to the bottom of this. Apologies that I can't give you more direct help, this project is quite big with lots of users and I'm only one person.

**Comment by TheButlah** [comment]
I'll try creating a more minimal reproducible example

**Comment by imsnif** [comment]
I'm pretty sure this is now fixed in main, will be released in the next release.

**Comment by TheButlah** [comment]
Installing the latest version of zellij from git did not solve this issue.

**Comment by imsnif** [comment]
Could you please copy the literal string you're setting up as your editor? Otherwise it's just guesswork :)

**Comment by TheButlah** [comment]
Here you go. I did some further exploration, and I've identified that the scrollback fails only when starship is used as the terminal prompt. Should I rename this issue or open a separate issue for that? Should I open an issue on starship's repo instead? I can't tell if its a zellij issue or a starship one.

```
ryan@ryan-macbook ~ % cat ~/.zshrc
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

plugins=(
        git
        zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Use starship prompt
# eval "$(starship init zsh)"
# Open Zellij in every shell
eval "$(zellij setup --generate-auto-start zsh)"

# enable vi keys
set -o vi

# Used by espressif toolchain for rust
source /Users/ryan/export-esp.sh

# Fast node manager
eval "$(fnm env --use-on-cd)"
ryan@ryan-macbook ~ % cat ~/.zshenv
. "$HOME/.cargo/env"
export VISUAL="/opt/homebrew/bin/nvim"
ryan@ryan-macbook ~ % zellij --version
zellij 0.36.0
ryan@ryan-macbook ~ % starship --version
starship 1.13.1
branch:
commit_hash:
build_time:2023-03-10 23:42:58 -05:00
build_env:rustc 1.68.0 (2c8cc3432 2023-03-06),stable-aarch64-apple-darwin
ryan@ryan-macbook ~ %
```

**Comment by imsnif** [comment]
No worries, glad it's working. Would still be curious to know what was in that `which nvim` that was causing this
