### ISSUE TITLE
scroll back buffer cause layout change

### ISSUE THREAD

**Issue by ixzh** [zellij-org/zellij#2774]
when scrolling back, some random key press were issued and layout keeps on changing:

<img width="236" alt="image" src="https://github.com/zellij-org/zellij/assets/14981695/52b67de9-9354-4a2c-ae57-1025f5533a51">

**Comment by owlkward** [comment]
I have a similar issue (maybe the same) on Arch Linux Kitty.
Zellij version: zellij 0.42.1
Kitty version: 0.41.1
Reliably reproducible with these steps:
Have two panes open. Enter Fullscreen and scroll back in one pane. Switch to the other pane and type something. Switch back to the original pane. After this parts of the output of following commands just vanishes and sometimes a fragment of an escape code is shown, but the exact code differs from time to time.
The layout is unnaffected by this in my case though.

**Comment by jgiannuzzi** [comment]
This should have been fixed in #4623, merged in `main`. Would you be able to validate it by building Zellij from source @ixzh @owlkward?

**Comment by owlkward** [comment]
It seems the issue is unchanged by the PR. I just cloned the repo and ran `cargo xtask run` and could still reproduce it.

BUT: The behavior is different now to what I originally reported, even with zellij version 0.43.1: instead of the output of the following commands vanishing it just prepends an escape code every time, e.g. for `zellij --version` I get `^[[44;32Rzellij 0.43.1`.
The escape code now also has a pattern, its always something like `^[[44;*R`. The same happens with version `0.44.0` from `main`.
This is way less annoying, because its mostly an aesthetic problem now, since you can at least still see the output of the commands, but there still seems to be an issue with correctly handling this case.
Maybe I will find time on the weekend to do a bisect to see when the behavior changed to maybe get a better idea where the problem is.

**Comment by jgiannuzzi** [comment]
@owlkward would you be able to provide a video showing the issue? I have tried the steps you described on kitty 0.45.0 on macOS and couldn't reproduce it.
