### ISSUE TITLE
Pane freezes when scrolling extremely long lines

### ISSUE THREAD

**Issue by giyany** [zellij-org/zellij#3207]
This used to cause Zellij to crash and on version 0.39.2 causes a pane to freeze.

When attempting to scroll through output with extremely long lines, the pane freezes and responds after about 30 seconds. After breaking, the behavior will persist (so long as whatever was on stdout is the same).
In a specific example, the line is 63 million characters long.

Version is 0.39.2, Alacritty terminal on ubuntu 20.04.6.

Maybe relevant: the ability to scroll through a line of that length is not that useful. More often than not, this string is sent to stdout as a test or by mistake, in both cases losing the ability to scroll is an annoyance.

**Comment by imsnif** [comment]
Thanks for the report! This should be fixed in the next version by https://github.com/zellij-org/zellij/pull/3045 (and the following PRs linked inside it).

**Comment by awsms** [comment]
I'm still facing this, though the freeze only lasts ~10seconds
