### ISSUE TITLE
Backspace in entersearch mode

### ISSUE THREAD

**Issue by xdavidel** [zellij-org/zellij#4024]
# Issues with the Zellij behavior.

`zellij --version`: zellij 0.41.2

`stty size`: 50 190

`uname -av`: Linux 6.11.5-zen1 #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux

## Issue description

Trying to delete characters from search query using backspace (or something else) does not work.

## Minimal reproduction

This issue can be reproduce by:
1. Entering the scroll mode
2. Follow to entersearch mode
3. Start typing a query
4. Try to delete some of the text in the search query

**Comment by imsnif** [comment]
Works for me...

**Comment by xdavidel** [comment]
Any ideas what I can try / do to debug this?
Can something from the log help?

**Comment by xdavidel** [comment]
This issue seems to only happen using kitty.

**Comment by vitordhers** [comment]
Same problem here on Ghostty 1.1.2-arch.

**Comment by Saplyn** [comment]
I don't know how to fix this problem, but I have some discoveries that might help.

**First discovery** is that: `backspace` when renaming tab (and in search mode I believe) *doesn't work* in `zellij` when I'm using [Ghostty](https://ghostty.org/) (it does nothing), but *works* when I'm using [Gnome-Terminal](https://gitlab.gnome.org/GNOME/gnome-terminal), [Gnome-Console](https://gitlab.gnome.org/GNOME/console), [kitty](https://sw.kovidgoyal.net/kitty/) or [`tmux`](https://github.com/tmux/tmux) (using `tmux` inside any terminal). All above terminal (and `tmux` the application) uses `^?` for backspace (inferred from the output of `infocmp -x`, which says `kbs=^?`.

**Second discovery** is that: I cannot type out `^?` (to delete characters) by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>?/</kbd> when I'm using `zellij` inside Ghostty or Kitty (it types `^_` instead`, but can do so when I'm using Gnome-Terminal. All terminal can delete characters by doing the key combo when outside of `zellij`. Gnome-Console pops-up a help window when I presse the key combo so sadly it can't be tested.

**Third discovery** is that: Might sounds stupid, but setting env-var `TERM` to `xterm-256color` doesn't help (when using Ghostty).

Also, here are the first line of `infocmp -x` of every terminal

- Gnome-Terminal: `xterm-256color|xterm with 256 colors,`
- Gnome-Console: `xterm-256color|xterm with 256 colors,`
- Tmux: `screen-256color|GNU Screen with 256 colors,`
- Ghostty: `xterm-ghostty|ghostty|Ghostty,`
- Kitty: `xterm-kitty|KovIdTTY,`

Hope these would be helpful?

**Comment by efeguerrero** [comment]
I was having this issue as well but I found a solution.

Zellij: `0.42.2`
Ghostty: `1.1.3`
Ubunt: `24.04`

Backspace was not working in entersearch mode with Ghostty until I toggled `Num Lock`.
For some reason it gets blocked while in other terminals like Alacritty it always works.

**Comment by mohseenrm** [comment]
Noticing the same with `zellij@0.43.0` but on reverting to `zellij@0.42.0` the issue seems to go away 😅

**Comment by russellpierce** [comment]
Fixed in 0.43.1 https://github.com/zellij-org/zellij/pull/4346

**Comment by Saplyn** [comment]
`zellij 0.43.1`, don't think it's fixed, but I'm seeing some differences)

<img width="758" height="256" alt="Image" src="https://github.com/user-attachments/assets/71ee2fa6-fe70-4016-8bf0-dd907139a2f1" />

---

Edit: Ghostty version

```text
Ghostty 1.2.0-arch1

Version
  - version: 1.2.0-arch1
  - channel: tip
Build Config
  - Zig version   : 0.14.1
  - build mode    : builtin.OptimizeMode.ReleaseFast
  - app runtime   : apprt.Runtime.gtk
  - font engine   : font.main.Backend.fontconfig_freetype
  - renderer      : renderer.generic.Renderer(renderer.OpenGL)
  - libxev        : io_uring
  - kernel version: 6.12.48-1-MANJARO
  - desktop env   : gnome
  - GTK version   :
    build         : 4.18.6
    runtime       : 4.18.6
  - libadwaita    : enabled
    build         : 1.7.7
    runtime       : 1.7.7
  - libX11        : enabled
  - libwayland    : enabled
```

**Comment by russellpierce** [comment]
Interesting, it was for Alacrity, but maybe terminals differ?

**Comment by Saplyn** [comment]
Maybe? I'm using Ghostty. Also, it looks like every "escaped key"/"functional key" is messed up: 

<img width="749" height="367" alt="Image" src="https://github.com/user-attachments/assets/feb396f7-c769-4766-a8f8-62f032b9107e" />

(I pressed up, down, left, right. backspace & delete)

**Comment by mskemalfasya** [comment]
same here in ghostty

<img width="689" height="355" alt="Image" src="https://github.com/user-attachments/assets/f830f4cd-cf69-4e21-b316-f1ad181ce943" />

**Comment by MakeShiftArtist** [comment]
Still having this issue, also in ghostty.

Pressed in order: Backspace, left arrow, up arrow, down arrow, right arrow, and delete.

<img width="636" height="138" alt="Image" src="https://github.com/user-attachments/assets/2a9fe1f6-6dd2-40d3-93c3-54e93e777c17" />

At this point I'm not sure which program this falls on. I'd assume it's ghostty given that it seems to be the only one *still* having this issue

**Comment by xyven1** [comment]
+1 on this issue, again on ghosttty (1.2.2).
