### ISSUE TITLE
Bug: ctrl-c closes a pane

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#54]
Need to investigate why. My guess is that we interpret it as SIGINT and then send a SIGINT to the pane rather than sending it ctrl-c and letting it decide what to do with it. But it's just a guess :)

**Comment by henil** [comment]
Also, something is causing `panic` whenever someone `Ctrl+c`s when there is some buffered text on the prompt.
I think that is related and I am looking into it.

**Comment by henil** [comment]
Today I noticed that this only happens in fish. I have even tried it on `nushell`. Do we handle fish shell differently? Or this is a `fish` issue?

**Comment by imsnif** [comment]
We don't handle any sort of shell differently. As I wrote in the original issue, I guess this has to do with forwarding of SIGINT. Specifically here probably: https://github.com/mosaic-org/mosaic/blob/main/src/os_input_output.rs#L77 (but of course, maybe I'm wrong).

**Comment by henil** [comment]
Talked to one of the fish maintainer and they pointed me to: https://github.com/fish-shell/fish-shell/issues/6828

Should be fixed in `fish` version `3.2.0`

**Comment by qballer** [comment]
This happens to me in both fish/bash and zsh. this bug isn't related to fish. 
It's unfortunate as it makes zellij really hard to use for me.

**Comment by imsnif** [comment]
@qballer - as discussed on discord we found that this is indeed the same fish issue and that it's resolved in fish >3.2.0, right?

**Comment by qballer** [comment]
Yea. upgrading fish manually fixed the issue, we can close this.

**Comment by computersrmyfriends** [comment]
I am facing the same issue on a specific saved session in Zellij in bash within wsl2.
It doesn't happen on new sessions. I think this bug is still present.

**Comment by chrislodev** [comment]
I'm seeing this behaviour in Wezterm, Ubuntu 22.04.
