### ISSUE TITLE
Pasting inside a program inside zellij sometimes adds control-characters

### ISSUE THREAD

**Issue by jovandeginste** [zellij-org/zellij#856]
When pasting inside a program inside zellij, I (sometimes) get extra ANSI(?) control characters surrounding the pasted text.

Seen with ao. `cat`, `hexdump`, and annoyingly: `pinentry-curses`... (to unlock my GPG key)

Not with: `vim`, `neovim`, etc.

**Basic information**

`zellij --version`: zellij 0.20.0, default configuration
`tput lines`: 57
`tput cols`: 118
`uname -av` or `ver`(Windows): Linux xyz 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Tue Nov 2 10:34:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

List of programs you interact with as, `PROGRAM --version`:
- `cat (GNU coreutils) 8.30`

**Further information**

Example, after copying `somestring` to my clipboard, using shift+insert to paste it:

```bash
➤ echo somestring
somestring
➤ cat
^[[200~somestring^[[201~
somestring
```

**Comment by jovandeginste** [comment]
FWIW, I see the same behaviour with different terminal emulators (gnome-terminal, tilix)

**Comment by imsnif** [comment]
Hey, sorry about the experience! This was a regression that was caused by me sleep coding. It should be fixed in 0.20.1. I'm closing this issue for now, let me know if it persists.

**Comment by jovandeginste** [comment]
Don't sweat it, I'm still test driving this nice tool!

**Comment by hackerchai** [comment]
still exists in v0.21.0 on MacOS Monterey, when I paste something into zellij terminal

**Basic Information**
`zellij --version`: zellij 0.21.0,  default configuration
`tput lines`: 33
`tput cols`: 119
`uname -av`: Darwin Hackerchai-MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41
.5~1/RELEASE_X86_64 x86_64

**Comment by imsnif** [comment]
@hackerchai - this is fixed in main but we haven't released a version yet. I plan to release one tomorrow.

**Comment by imsnif** [comment]
Actually, this specifically was a different issue, but there was a similar issue that's fixed in main and not released yet :D I'm guessing that's the one you're referring to. If you'd like to compile from main and give it a try to be sure that'd be cool, otherwise try and wait for the release and see then. If somehow this frankenstein issue comes back again, we'll sort it out.
